[package]
name = "jkl"
description = "Asset compression and packing tool"
documentation = "https://docs.rs/jkl"
repository = "https://github.com/zakarumych/jkl"

version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hashbrown.workspace = true
smallvec.workspace = true
