[workspace]
members = ["cli", "experiments"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
hashbrown = "0.16"
egui = "0.33"
eframe = "0.33"
image = "0.25.8"
smallvec = "1.15"

[package]
name = "jkl"
description = "Asset compression and packing tool"
documentation = "https://docs.rs/jkl"
repository = "https://github.com/zakarumych/jkl"

version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hashbrown.workspace = true
smallvec.workspace = true
