[package]
name = "jkl-experiments"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
jkl = { path = ".." }
eframe = { workspace = true, features = ["persistence"] }
image.workspace = true
rand.workspace = true
egui.workspace = true

egui-snarl = { version = "0.9", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
